### ISSUE TITLE
Invalid v3 private key

### ISSUE THREAD

**Issue by davidtavarez** [cmehay/pytor#6]
Hi! First, Great job!

Actually I'm trying to use `pytor` to generate a v3 onion URL for https://github.com/cmehay/docker-tor-hidden-service but I'm not able to use the key.

![Screenshot from 2019-07-17 18-27-59](https://user-images.githubusercontent.com/337107/61416186-deffbd00-a8c0-11e9-8390-800464f63b3c.png)

I did test the `docker-tor-hidden-service` with a key generate by https://github.com/cathugger/mkp224o and the key was perfectly accepted.

**Comment by cmehay** [comment]
Hi,

I'm sorry I cannot reproduce your issue.

`pytor` is used internally in https://github.com/cmehay/docker-tor-hidden-service to generate keys, so it would work as expected.

Can you provide more details?

**Comment by davidtavarez** [comment]
```bash
$ git clone https://github.com/cmehay/pytor.git
$ cd pytor
$ virtualenv -p python3 venv
$ source venv/bin/activate
$ pip install fire 
$ pip install PyYaml 
$ pip install pycrypto
$ pip install pycryptodome
$ mkdir safer
$ python pytor new-hidden-service safer --version  3
FYI: Binary data is base64 encoded
path:
safer
hostname:
ofcsgfmnkv5jf3da6haluxxkm2vcb4rtynad2dbl5vnaf3emry6e27id.onion
hs_ed25519_secret_key:
PT0gZWQyNTUxOXYxLXNlY3JldDogdHlwZTAgPT0AAACw5JteWWx3vkzsoLB8Vlhout2Dp2OTmHgbAW3NgoByXl9nTA7qWkqnC+O47wr7cC3qfqA0PINnM+mqe23DD9E5
hs_ed25519_public_key:
PT0gZWQyNTUxOXYxLXB1YmxpYzogdHlwZTAgPT0AAABxRSMVjVV6kuxg8cC6XupmqiDyM8NAPQwr7VoC7IyOPA==
```

So I took: `PT0gZWQyNTUxOXYxLXNlY3JldDogdHlwZTAgPT0AAACw5JteWWx3vkzsoLB8Vlhout2Dp2OTmHgbAW3NgoByXl9nTA7qWkqnC+O47wr7cC3qfqA0PINnM+mqe23DD9E5` and added here: https://github.com/davidtavarez/safer/pull/2/files and it works now!

Sorry!
